version: '3'
services:
  app:
    image: ghcr.io/logicleai/logicle:latest
    restart: always
    environment:
      PORT: 80
      APP_URL: ${APP_URL}
      DB_ENGINE: ${DB_ENGINE}
      DATABASE_URL: ${DATABASE_URL}
      NEXTAUTH_URL: ${NEXTAUTH_URL}
      NEXTAUTH_SECRET: ${NEXTAUTH_SECRET}
    ports:
      - 80:80
    volumes:
      - sqlite-data:/db

volumes:
  sqlite-data: